### ISSUE TITLE
Broken on Rails 2.3

### ISSUE THREAD

**Issue by stouset** [danpal/attr_encryptor#1]
https://github.com/danpal/attr_encryptor/blob/master/lib/attr_encryptor/adapters/active_record.rb#L17

This method will never get called. It's provided in a module, but because `attr_encryptor` is _already defined_ in the class it extends, that method will take priority. Example:

``` ruby
class Foo
  def self.ponies
    'ponies'
  end
end

class Bar
  def ponies
    super + '  rock'
  end
end

Foo.extend Bar
Foo.ponies # => 'ponies'
```

Since the `Foo::ponies` method already exists, the one in `Bar` is never delegated to. This needs to be wrapped around the original via `alias_method_chain` or similar.

**Comment by danpal** [comment]
This happens to you in Rails 2.3?
I wish I could support Rails 2.3, but it's too old, I don't even have a copy of ruby 1.8 anymore, but if you send me a pull request I'll merge it.

**Comment by danpal** [comment]
Thanks for the pull request. I tested on ruby 1.9 and Rails 3.1. I have not checked if this works on Rails 2.3 (or ever will), but hopefully it does.
