### ISSUE TITLE
Key generation

### ISSUE THREAD

**Issue by sashman** [danpal/attr_encryptor#10]
Hey I ran into a problem with the key generation. I have 

``` ruby
attr_encrypted  :col_int, :key => 'key', :if => :encryption_required, :marshall => true
```

That runs fine and creates the object with the encrypted attribute. However when I restart the console session, I get a bad decrypt error. Is this related to how the key is generated? As in will the new session create a new object for the 'key' string which will then cause the key to be invalid?

**Comment by danpal** [comment]
No. This looks correct. You have a bug in your database. Did you create a col_int_salt?
