### ISSUE TITLE
Saving Salt/IV in Database - Security Risk?

### ISSUE THREAD

**Issue by threadhead** [danpal/attr_encryptor#11]
I am far from a security expert, but doesn't saving the salt and vi in the database give any potential thief a great head start on decrypting an encrypted attribute? Seems pretty unlikely that they would only steal the encrypted attribute string if they gain access to a table.

Would it not be significantly safer to store a single salt as an environment variable? Even the key too.

And I'm pretty sure that if one is aiming for PCI compliance, storing the salt in the db is a big no no.

**Comment by ndbroadbent** [comment]
See this SO answer: http://stackoverflow.com/a/878569/304706

> The purpose of a salt is to require the regeneration of a rainbow table per password. If you use a single salt, the hacker/cracker only has to regenerate the rainbow table once and he has all your passwords. But if you generate a random one per user, he has to generate one per user. Much more expensive on the hackers part. This is why you can store a salt in plain text, it doesn't matter if the hacker knows it as long as there's more than one.
> 
> Security by obscurity is not good, microsoft has taught us that.

**Comment by danpal** [comment]
Yes, what ndbroadbent said. Storing the salt in the ENV would be really painful and won't won't give you better security. Also storing a salt in the db is fine for PCI compliance, in fact is a industry standard.
