### ISSUE TITLE
New gem for encryption...

### ISSUE THREAD

**Issue by ronalchn** [danpal/attr_encryptor#16]
Hi. So I was trying to make a gem for compression purposes. But as I worked on it, and started thinking about increasing its capabilities, I began thinking about hashing, encoding, error checking and encryption.

Essentially, I've written a gem https://github.com/ronalchn/codify, that supports arbitrary encoders. I am still working on  some missing features, but perhaps it might be of interest as I work on full encryption support (without needing to write custom encoders).

**Comment by danpal** [comment]
this is not a bug.
