### ISSUE TITLE
Use a new IV for each encryption

### ISSUE THREAD

**Issue by namelessjon** [danpal/attr_encryptor#17]
Currently the library appears to generate an IV once and then reuse that for all future encryptions.  Since the key generated is also static (salt is also generated once, and the passphrase is static), this results in a key/iv pair being reused (potentially very many times).  This compromises the security of the cipher, potentially revealing details of the encrypted contents to an attacker.  It should instead be randomly generated and stored each time the encrypted attribute changes.

**Comment by danpal** [comment]
You should pass a different IV and Salt everytime. There no reason no to do so. iv salt are stored in the DB. Loot at:

<pre><code>
      attr_reader (encrypted_attribute_name.to_s + "_iv").to_sym unless instance_methods_as_symbols.include?((encrypted_attribute_name.to_s + "_iv").to_sym )
      attr_writer (encrypted_attribute_name.to_s + "_iv").to_sym unless instance_methods_as_symbols.include?((encrypted_attribute_name.to_s + "_iv").to_sym )
      attr_reader (encrypted_attribute_name.to_s + "_salt").to_sym unless instance_methods_as_symbols.include?((encrypted_attribute_name.to_s + "_salt").to_sym )
      attr_writer (encrypted_attribute_name.to_s + "_salt").to_sym unless instance_methods_as_symbols.include?((encrypted_attribute_name.to_s + "_salt").to_sym )
</code></pre>

If you have encrypted_password. Then automatically encrypted_password_iv and encrypted_password_salt are store. Naturally you have to create this fields in the database, but it will all be handled automagically for you

**Comment by namelessjon** [comment]
The code seems to correctly handle the case between attributes, since each model instance should, thanks to those columns, get a new IV and salt for each attribute.  However, if I edit a value and resave it, the same key/iv pair will be reused, which is not correct.

**Comment by jjasonclark** [comment]
As a work around you can set the encrypted_XXX_iv value to nil to force regeneration when writing a new value.

**Comment by namelessjon** [comment]
It shouldn't be a 'work around', though.  If you're writing a library that supposedly offers easy crypto, you should do it right.  And for AES in CBC mode, that requires an unpredictable IV.  (It should also check the integrity of the ciphertext, but if the attacker is writing to the DB, you have bigger problems than the fact the crypto is broken.)

**Comment by danpal** [comment]
I don't think there is any issue in re-using IV's and Salts as long as they are unique. Can you explain why you think is worth regenerating them?

**Comment by namelessjon** [comment]
Reusing the same IV with the same key (which is what you get from using the same salt), leaks information about the first block of the message - is part of it the same or different?  It might be okay in this instance, if you're not expecting the attacker to get more than one look at the database.  At least with CBC mode.

If someone decides to use AES-CTR mode (supported in more modern ruby/openssl builds), reusing the IV could completely compromise the confidentiality of the data.

The same salt is okay.  Though as an aside,  I wonder why you're using a salt and PBKDF at all. You can generate a 256-bit random key from `/dev/random` and use that for the app.  It will be quicker (no need to iterate the PBKDF) and more secure (more entropy than a passphrase).  PBKDF is only used because humans are normally pretty bad at remembering passwords of sufficient complexity to be secure.  Since the passphrase is never typed by a human, why not use a real key?

**Comment by danpal** [comment]
You are right that it will leak the first block if it were the same although the previous version is already destroyed so I think this is a very small deal. The idea that the attacker will have multiple DB copies to check if someone leaks the initial block is really not a rational concern.

Why are we using PDBDF? Because the implementation doesn't assume from were the key comes from. In our case the key does in fact come from a user typed string. If you are generating keys randomly and storing them I do think you are right and it would be better just to ask openssl to generate you a random key. Now the big problem is, were do you store the key? Truth is the user's head is still a pretty secure storage place.

**Comment by namelessjon** [comment]
What is the threat model this encryption is intended to protect against, regarding the IV?  Theft/loss of a lone database backup? (I'm not saying this is a bad threat model, but curious as to what it is)

With they key, I was going off the code examples, many of which seem to have a hard-coded passphrase in the application code, so the place to store the key appears to be "The application code".  Or "an Enviromental Variable" might work too.

If you're dealing with user-entered keys (some kind of 'give us your password and we promise to throw it away after we use it' deal?), then of course a PBKDF method should be used.

**Comment by danpal** [comment]
Yes, IV is use to protect from the loss of the DB and the attacker using rainbow tables to figure out the values. Also it protects around duplicate entries have same final encrypted value
