### ISSUE TITLE
order of `attr_entryptor` and `store` calls seems to matter

### ISSUE THREAD

**Issue by eprothro** [danpal/attr_encryptor#20]
It appears that if `attr_encrypted` is called before ActiveRecord::Base's `store`, the store will sometimes return as a `struct` instead of a `Hash`.

``` ruby
  attr_encrypted :ssn, :key => encryption_secret
  store: :foo
```

```
#<struct ActiveRecord::AttributeMethods::Serialization::Attribute coder=#<ActiveRecord::Coders::YAMLColumn:0x007faf708bec38 @object_class=Hash>, value=nil, state=:serialized>
```

Reordering to declare the store before the encrypted attribute seems to work around the issue.

``` ruby
  store: :foo
  attr_encrypted :ssn, :key => encryption_secret
```

Apologies for the lack of failing test or PR, only had time to report, in case others run into this, at the moment :/

**Comment by danpal** [comment]
Please issue a pull request or a failing test. I am really busy at the moment, don't really have enough time to investigate this issues.

**Comment by eprothro** [comment]
I understand, we're all very busy; apologies for not having the time to submit a PR or failing test. Does it not make sense to leave this open for others to learn / avoid / possibly fix?

**Comment by zauberware** [comment]
Just ran into that issue and debugged a whole day. I would propose to integrate that into the man page.
