### ISSUE TITLE
OpenSSL::PKCS5 not found on jruby 1.6.7

### ISSUE THREAD

**Issue by colindean** [danpal/attr_encryptor#3]
Getting this error when storing data in the encrypted variable.

**Comment by colindean** [comment]
I traced it down to actually be in the Encryptor class that's a part of the encryptor2 gem:

https://github.com/danpal/encryptor/blob/master/lib/encryptor.rb#L57

`jruby-openssl`, the gem which provides OpenSSL to jruby, lacks OpenSSL::PKCS5. OpenSSL:PKCS7 doesn't include the method called there, so it's not a drop-in replacement.

**Comment by colindean** [comment]
My workaround involves using a simple encryption class I'd planned to use before I found attr_encrypted/attr_encryptor. It's kinda ugly-- could be refactored.

```
attr_encrypted :api_password, :key => @@key, :encryptor => Cryptor
```

Cryptor#encrypt and Cryptor#decrypt simply take a hash with :key and :value set.

```
class Cryptor
    @@encryption_type = "aes-256-cbc"
    def self.encrypt(options)
      plaintext = options[:value]
      key = options[:key]
      cipher = OpenSSL::Cipher::Cipher.new(@@encryption_type)
      cipher.encrypt
      cipher.key = key
      cipher.iv = iv = cipher.random_iv
      encrypted = cipher.update(plaintext) + cipher.final
      encrypted = iv + encrypted
      encrypted = Base64.encode64(encrypted)
      encrypted
    end
    def self.decrypt(options)
      encrypted = options[:value]
      key = options[:key]
      cipher = OpenSSL::Cipher::Cipher.new(@@encryption_type)
      cipher.decrypt
      cipher.key = key
      encrypted = Base64.decode64(encrypted)
      cipher.iv = encrypted.slice!(0,cipher.iv_len)
      decrypted = cipher.update(encrypted) + cipher.final
    end
end
```

**Comment by colindean** [comment]
I'd file this on your encryptor fork, @danpal, but alas, Github doesn't let you file issues on forks!

**Comment by danpal** [comment]
Sorry I don't plan to support JRuby. You need PKCS5 to use encryptor, thats the way it should be.

**Comment by colindean** [comment]
Is there a cryptographical reason that PKCS5 is essential? I'll readily admit that my knowledge of such things is likely less than yours!

It's OK if you have no interest in supporting JRuby; my class above suits my needs for now. However, if there's some kind of weakness in my approach, I'd like to know. A difference I see is that I'm not using the iv supplied, instead generating a random one and prepending it to the encrypted output.

**Comment by joerichsen** [comment]
I got it working under jruby by adding the following snippet of code to an intializer in my Rails app: https://gist.github.com/4410238

Furthermore, I had to change the algorithm to "aes-128-cbc" in order to get it working, but that might just be a limitation on the jvm I use.
