### ISSUE TITLE
foo

### ISSUE THREAD

**Issue by maletor** [danpal/attr_encryptor#5]
https://github.com/danpal/attr_encryptor/blob/master/lib/attr_encryptor.rb#L296-298

**Comment by lyahdav** [comment]
I created a pull request for this: https://github.com/danpal/attr_encryptor/pull/8
We discovered this by running "nil.respond_to? :foo" and seeing it returned true and not understanding how that could be.

**Comment by maletor** [comment]
Damn, that sucks.

**Comment by maletor** [comment]
It's gone now.
