### ISSUE TITLE
Order of attributes

### ISSUE THREAD

**Issue by maletor** [danpal/attr_encryptor#6]
Did you ever resolve the order of attributes issue?

**Comment by danpal** [comment]
In your model on initialize make sure attributes that require keys are processed at the end. For example password.
 <pre><code> 
  #the password requires a key, so :password has to be the
  #last attr that is processed 
  def initialize(*args)
    attr = args[0]
    if(attr && attr[:password]) 
      #put password at the end of the hash
      password = attr[:password]
      attr.delete(:password)
      attr.merge!(:password => password)  
    end
    args[0] = attr
    super(attr)
  end 
</code></pre>

**Comment by maletor** [comment]
Ya I"m running 1.8.7 so Hash order is definitely an issue. Overriding initialize is usually frowned upon with AR. I tried `ActiveSupport::OrderedHash.new.merge(attributes)` but it was still mixing them up.

Any idea on how to make this test pass? https://github.com/danpal/attr_encryptor/blob/master/test/active_record_test.rb#L95

**Comment by danpal** [comment]
I tried for a full day a couple of months ago, looking into ActiveRecord closely but there was no "clean" way of doing it, sorry.

**Comment by maletor** [comment]
I too tried for a full day.

On Apr 19, 2012, at 9:01 PM, Daniel Palacio
reply@reply.github.com
wrote:
