### ISSUE TITLE
Bad decrypt

### ISSUE THREAD

**Issue by timsaunders** [danpal/attr_encryptor#9]
Hi,
I am using your gem as apart of a attribute within my model. It seems to encrypt the value correctly, however when I try to decrypt the same value it returns a "err: bad decrypt" message. Been looking into this issue for days, would love some insight into the decrypting.
Thanks

**Comment by danpal** [comment]
The docs are pretty good. Perhaps ask in stackoverflow and send me a link. I can't help you with such little info.

**Comment by timsaunders** [comment]
Found the issue!! I had a model called Card and had an attribute on it called number. 
I was using the decrypt_number() to get the decrypted value, however it was returning the incorrect value. However calling number directly worked fine. 
For some reason the decrypt_{attribute}() method doesn't seem to work. 
Hope this helps anyone with the same issue

**Comment by danpal** [comment]
Yes the whole point of the project if to do encryption and decryption transparently. Readme explains it.
